FROM centos

ENV PATH=$PATH:/usr/local/go/bin

RUN rm -f /etc/yum.repos.d/*repo && \
	curl -o /etc/yum.repos.d/private.repo http://gitlab.local.io/private.repo && \
	curl -k -o go.tar.gz -L https://dl.google.com/go/go1.9.3.linux-amd64.tar.gz && \
	tar -C /usr/local -xzf go.tar.gz && \
	yum install -y git gcc && \
	mkdir -p /root/go/src/github.com/coreos/etcd && \
	mkdir -p /root/go/src/go.etcd.io/etcd && \
	git config --global http.sslVerify false && \
	go get gotest.tools/assert
RUN git clone https://github.com/coreos/etcd.git /root/go/src/github.com/coreos/etcd
RUN git clone https://github.com/etcd-io/etcd.git /root/go/src/go.etcd.io/etcd
RUN go install github.com/coreos/etcd

WORKDIR /root

COPY . ./

RUN go build main.go

CMD ["./main"]
