apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  generation: 1
  labels:
    ipfailover: havip-keepalived
  name: havip-keepalived
  namespace: havip
spec:
  replicas: 2
  selector:
    ipfailover: havip-keepalived
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        ipfailover: havip-keepalived
    spec:
      containers:
      - env:
        - name: OPENSHIFT_HA_CHECK_INTERVAL
          value: "3"
        - name: OPENSHIFT_HA_CONFIG_NAME
          value: hazone1
        - name: OPENSHIFT_HA_IPTABLES_CHAIN
          value: INPUT
        - name: OPENSHIFT_HA_MONITOR_PORT
          value: "0"
        - name: OPENSHIFT_HA_NETWORK_INTERFACE
        - name: OPENSHIFT_HA_USE_UNICAST
          value: "false"
        - name: OPENSHIFT_HA_VIRTUAL_IPS
          value: 192.168.0.11,192.168.0.12,192.168.0.13
        - name: OPENSHIFT_HA_VRRP_ID
          value: "123"
        - name: VIP_INTERFACE
          value: eth0
        - name: HAVIP_CONTROLLER_ENDPOINT
          value: havip-controller.havip.svc.cluster.local:8080
        - name: HAVIP_HOSTS_SVC
          value: havip-hosts
        - name: NAMESPACE
          value: havip
        image: harbor.poc.com/openshift/havip-keepalived:v3.9.1
        imagePullPolicy: Always
        name: hazone1-keepalived
        ports:
        - containerPort: 63123
          hostPort: 63123
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        ipfo: zone1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
  test: false
  triggers:
  - type: ConfigChange
